### ISSUE TITLE
Performance problems in scene

### ISSUE THREAD

**Issue by PKVISIONS** [t3kt/raytk#1150]
So my render keeps getting stuck in 30 fps and the graphics card is used at 100% capacity all the time. I've figured some things out to make it less but i would really appreciate any info from anyone that knows what is up with this. Thanks!!!

**Comment by t3kt** [comment]
Can you provide a file or at least some details about what you're trying that's causing issues?
Is it everything that uses RayTK? Or just a specific setup?
What version of TD and of RayTK?

**Comment by PKVISIONS** [comment]
TD version is 2023.11290 and RayTK is 0.37. It's lagging a lot and it is stuck in 30 fps. I will attach the TD file so you can see if you have the same problem and tell me solutions. [https://we.tl/t-uYOnQBmBNX]. You can download the .toe file here. Thanks for any help!!!

**Comment by t3kt** [comment]
What GPU are you using?
I'm getting 60fps on both a desktop 3080Ti and a laptop 4070.

**Comment by t3kt** [comment]
Have you tried replacing the combine and everything upstream of it with a sphere and see what the frame rate is with that?

**Comment by PKVISIONS** [comment]
No actually I haven't tried that. Can you please ellaborate on how to do that? I'm sorry but i'm pretty much a beginner will try to figure it out slowly but surely.

**Comment by t3kt** [comment]
1. Open the RayTK palette with ALT+R.
2. Type in sphereSdf and hit enter
3. Connect the sphereSdf operator to the first input on the raymarchRender3d

**Comment by PKVISIONS** [comment]
But the ModularMat is connected to the first input when I change that the whole render is gone. Or do you mean something else?

**Comment by t3kt** [comment]
<img width="408" alt="image" src="https://github.com/t3kt/raytk/assets/894413/b05c0cf4-f9d6-426c-9cf4-ebbb2e8adbe5">

**Comment by PKVISIONS** [comment]
Yeah and how do I make the project have the same render as before. The face disappeared and I just have a sphere how do I have the same render and just fix the fps problem?

**Comment by t3kt** [comment]
The strategy is to try individual things to see what's causing the issue.
I think the first thing to try now that we've shown that a basic sphere is able to render fast, would be to try just the headSdf.  Keep the camera and light since there's animation on those. That forces it to cook every frame. Otherwise it would just render once and then sit there doing nothing at 60fps.
headSdf is one of the most complicated, so it's possible that whatever GPU you have just isn't able to handle it.
If headSdf works fine on its own, you could try just the juliaSdf.
Then try the juliaSdf with the bend+noiseField.
And so on.
