### ISSUE TITLE
Banding issue with render

### ISSUE THREAD

**Issue by catronomix** [t3kt/raytk#563]
Not sure if anyone else is experiencing this, but the raymarch renderer does not produce smooth gradients, there is always some banding going on as you can see in the screenshot

![image](https://user-images.githubusercontent.com/42138122/122644537-f9c6b600-d115-11eb-80ef-2d9c8d066d9e.png)

System info: 
Windows 10, TD 2021.13610, Raytk 0.14
Intel i7 11700k, 64mb ram, nvidia rtx 3090

**Comment by t3kt** [comment]
Thanks for the report! Yeah that's definitely an issue.
It's caused by having the `Surface Distance` setting being too high. It controls sort of the spatial "resolution" of surfaces. It's the distance at which a ray is considered to have "hit" a surface. In some scenes, setting it too low can cause performance issues.
Try setting it to 0 and if you have performance issues, bump it up a bit to 0.001 or so.
By default it's set to 0.01, which should be lower. I'll update the default to 0.001, which should be appropriate for most simple scenes.
